# Generated by Django 5.2.5 on 2025-08-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_item_item_category_item_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_category',
            old_name='cateogry',
            new_name='category',
        ),
    ]
